### PR TITLE
added stying to code in tutorials

### PR DESCRIPTION
**Pull request by celebilaw**

### CODE REVIEW

**Review by reginawang3495 — CHANGES_REQUESTED** [review]
I can take a look after @Nhamakami7 does if you want :)

**Review by Nhamakami7 — COMMENTED** [review]
hey celebi! i think it looks rly good for the most part. i have a few comments, through. i messed around w the code a bit, and i think that black might be a better color for the code instead of green. what do u think? also, i see there are a few long running lines in the code. i think for the sake of formatting, could u break those long-running lines into 2? also, for the break tags, i believe that u can just make them /<br /> instead of /<br></br>

**Comment by celebilaw** [comment]
Revised, please check

**Comment by reginawang3495** [comment]
I didn't even know how to see the tutorial, and had to fumble around even while knowing that it exists somewhere :0 

For UI/UX sake, I think we should have it open by default or something? @Nhamakami7

**Review by reginawang3495 — CHANGES_REQUESTED** [review]
I wonder if there's a way to make it colorful like the editor! not 100% sure there's an easy way to do this, so hmu if you can't figure it out for like 30 min or something :)

Also, there's a ton of changes in `package-lock.json`. I can also help you figure that out if you need help!

**Comment by celebilaw** [comment]
I can technically just make more CSS to style the syntax. I'm not sure if we want that.
or maybe I can look into using the imported libraries that we already have for the editor itself.
What should I do in packages-lock.json

**Comment by reginawang3495** [comment]
Oh I don’t think I mean more CSS, I think we can yoink what the editor does. I’ll look into it and let you know, in the meantime, feel free to ignore :)

Tbh the differences are because of node differences and you could fix that by installing the same versions, but it’s a hassle. I’d just revert the file with git commands. Lmk if you need help !!

**Comment by Nhamakami7** [comment]
Hey Celebi, sorry for the very late response. These changes look good! I can open another issue for having the tutorial open by default and making the tutorial look colorful like the editor.

**Comment by celebilaw** [comment]
Reverted package-lock.json changes

**Review by reginawang3495 — APPROVED** [review]
lgtm

**Pull request merged**
