### PR TITLE
Tooltip for hex code copy

### LINKED ISSUE #31: Tooltips for Copied on Hexcode Hover
Add a popup so it's more obvious to the user that a hexcode can be copied when it's hovered over.

### PR DESCRIPTION
**Pull request by Kyle-Pu**
Now shows glowing red icon next to the hexcode when the user first visits the page. Clicking on this will tell users that they can click on the hex code to copy it. Uses React Joyride. Closes #31

### CODE REVIEW

**Comment by Kyle-Pu** [comment]
It's only showing up when you refresh the page right now. Will fix

**Review by reginawang3495 — CHANGES_REQUESTED** [review]
I can take a look after @Nhamakami7 !

**Review by Nhamakami7 — COMMENTED** [review]
hey kyle, i think it looks really good! i have just a couple comments: 

do you know if it's possible to center the pop-up text? i think the way it looks rn with the text uncentered looks a little unpolished.
image

also, do u know if it's possible to make it so the popup only shows when we visit the page for the first time? or maybe so the popup only shows up once in total? i see that the popup shows up again every time u refresh the page. this isn't a big deal though.

**Review by reginawang3495 — COMMENTED** [review]
For the tutorial stuff + to address @Nhamakami7's comment about only having it pop up once, I'd maybe use something like `localStorage` like [this](https://github.com/uclaacm/selector-safari/blob/master/src/components/Textbox/Textbox.js#L23,L29).  Not only is it useful for it to not show up again, but it's also useful so that if teachers are sharing screen, you guys can have an option to skip all tutorials, or replay all tutorials and stuff like that

Unrelated to this, tix-wise, idk if you'd want players to only be able to skip levels if they've played it? (So save max level that each player has achieved) Or show an "Are you sure you want to skip?" note or something like that

**Comment by Kyle-Pu** [comment]
Closes #31

**Comment by Kyle-Pu** [comment]
Working on resolving conflicts with game walkthrough tooltips

**Comment by reginawang3495** [comment]
Don't forget to add "closes #31" in the PR description :)
image

**Pull request merged**
